### ISSUE TITLE
😈 [Feature Enhancement] - Enable updateChannelMeta to be invoked from CCR

### ISSUE THREAD

**Issue by 0xNilesh** [push-protocol/push-smart-contracts#403]
### Feature name

updateChannelMeta can only be invoked from core contract

### Describe the Enhancement

Enable updateChannelMeta to be invoked from CCR

### Contract Name

Comm Contract

**Comment by Zartaj0** [comment]
Included in https://github.com/push-protocol/push-smart-contracts/issues/411
